name: wf3
on: workflow_dispatch
jobs:
  greeting:
      name: greeting
      runs-on: ubuntu-latest
      steps:
        - name: run basch command
          run: echo "Hello World"
          shell: bash
